###############################################################################
# SOURCE   : ~/Sources/System/Config/dotfiles/zsh.conf
# TARGET   : ~/.zshrc
# DESC     : Configuration ZSH
###############################################################################
# --- ZINIT ---
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

# PATH
export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
export DOTFILES="$HOME/Sources/System/Config"
export REPOS="$HOME/Sources/Repos"

export GOROOT="/usr/local/go"
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

# Plugins
zinit ice wait"0" lucid
zinit light zsh-users/zsh-autosuggestions

zinit ice wait"0" lucid
zinit light zsh-users/zsh-syntax-highlighting

zinit ice wait"0" lucid
zinit light zsh-users/zsh-completions

# --- ALIASES ---
# Eza
alias ls='eza --icons'
alias ll='eza -lh --icons --git'
alias la='eza -la --icons --git'

# Bat
alias cat='bat --paging=never'
alias less='bat'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Git
alias gs='git status'
alias gp='git pull'
alias gcm='git commit -m'

# Clear
alias c='clear'

# --- STARSHIP ---
eval "$(starship init zsh)"
# --- ZOXIDE ---
eval "$(zoxide init zsh)"

