###############################################################################
# SOURCE   : ~/Sources/System/Config/ghostty.conf
# TARGET   : ~/.config/ghostty/config
# DESC     : Configuration de la console GhosTTY
###############################################################################
# --- Apparence ---
font-family = "JetBrainsMono Nerd Font"
font-size = 11
background-opacity = 0

# --- Raccourcis Clavier ---
keybind = ctrl+c=copy_to_clipboard
keybind = ctrl+v=paste_from_clipboard
# SIGINT
keybind = alt+c=text:\x03

# Gestion des onglets
keybind = ctrl+t=new_tab
keybind = ctrl+w=close_tab
keybind = ctrl+tab=next_tab
keybind = ctrl+shift+tab=previous_tab

# --- Curseur ---
cursor-style = block
# L'option exacte pour le clignotement
cursor-style-blink = true

# --- Souris ---
copy-on-select = true

# --- Zoom ---
keybind = ctrl+plus=increase_font_size:1
keybind = ctrl+minus=decrease_font_size:1
keybind = ctrl+à=reset_font_size