###############################################################################
# SOURCE   : ~/Sources/System/Config/keyd.conf
# TARGET   : /etc/keyd/default.conf
# DESC     : Remappage clavier pour Fedora
###############################################################################
[ids]
*

[main]
# Left Alt -> Left Ctrl
leftalt = leftcontrol

# Left Ctrl -> Left Alt
leftcontrol = leftalt

# Left Windows (Meta) -> Right Alt (AltGr)
leftmeta = rightalt

# Right Alt (AltGr) -> Left Windows (Meta)
rightalt = leftmeta