###############################################################################
# SOURCE   : ~/Sources/System/Config/zsh.conf
# TARGET   : ~/.zshrc
# DESC     : Configuration ZSH
###############################################################################
# --- ZINIT ---
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

# PATH
export PATH="$HOME/.local/bin:$PATH"
export DOTFILES="$HOME/Sources/System/Config"
export REPOS="$HOME/Sources/Repos"

export GOROOT="/usr/local/go"
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

# Plugins
zinit ice wait"0" lucid
zinit light zsh-users/zsh-autosuggestions

zinit ice wait"0" lucid
zinit light zsh-users/zsh-syntax-highlighting

zinit ice wait"0" lucid
zinit light zsh-users/zsh-completions

# --- ALIASES (Tes raccourcis) ---
alias ls='ls --color=auto'
alias gs='git status'
alias gp='git pull'
alias gcm='git commit -m'
alias c='clear'

# --- STARSHIP ---
eval "$(starship init zsh)"
